# Generated by Django 4.2.11 on 2024-09-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='category_id',
            new_name='category',
        ),
    ]
